import datetime


DEBUG = True
SECRET_KEY = ""
SECRET_KEY_FALLBACKS =  None
PERMANENT_SESSION_LIFETIME = datetime.timedelta(days = 31)
USE_X_SENDFILE = False
TRUSTED_HOSTS = None
SERVER_NAME = None
APPLICATION_ROOT = "/"
SESSION_COOKIE_NAME = "SID"
SESSION_COOKIE_DOMAIN = None
SESSION_COOKIE_PATH = None
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = False
SESSION_COOKIE_PARTITIONED = False
SESSION_COOKIE_SAMESITE = None
SESSION_REFRESH_EACH_REQUEST = True
MAX_CONTENT_LENGTH = None
MAX_FORM_MEMORY_SIZE = 500000
MAX_FORM_PARTS = 1000
SEND_FILE_MAX_AGE_DEFAULT = None
TRAP_BAD_REQUEST_ERRORS = None
TRAP_HTTP_EXCEPTIONS = False
EXPLAIN_TEMPLATE_LOADING = False
PREFERRED_URL_SCHEME = "http"
TEMPLATES_AUTO_RELOAD = None
MAX_COOKIE_SIZE = 4093
PROVIDE_AUTOMATIC_OPTIONS = True

SQLALCHEMY_ECHO = True
SQLALCHEMY_DATABASE_URI = "mysql+pymysql://"
SQLALCHEMY_POOL_SIZE = 8
SQLALCHEMY_MAX_OVERFLOW = 10

CACHE_TYPE = "RedisCache"
CACHE_REDIS_HOST = "localhost"
CACHE_REDIS_PORT = 6379
CACHE_REDIS_DB = 0
CACHE_DEFAULT_TIMEOUT = 300

SECURITY_PASSWORD_HASH = "des-cbc"
SECURITY_PASSWORD_SALT = ""
SECURITY_COOKIE_SALT = ""
